sudo: false
language: cpp
compiler:
  - clang
os:
  - linux
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic
    packages:
      - clang-7.0

before_install:
  - eval "CC=clang && CXX=clang++"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./test/tests/runTests